#goal definition
int32 command
sensor_msgs/PointCloud2 source_pointcloud
sensor_msgs/PointCloud2 target_pointcloud
---
#result definition
geometry_msgs/PoseStamped transformation_pose
---
#feedback
float64 percentage
